services:
  app:
    image: tms-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tms-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tms
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JWT_SECRET=VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkhMTIz
      - JWT_ACCESS_TOKEN_VALIDITY=3600000
      - JWT_REFRESH_TOKEN_VALIDITY=604800000
    depends_on:
      - db
    networks:
      - tms-network

  db:
    image: postgres:latest
    container_name: tms-db
    environment:
      - POSTGRES_DB=tms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - tms-db-data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - tms-network

networks:
  tms-network:
    driver: bridge

volumes:
  tms-db-data:
    driver: local
