services:
  db:
    image: postgres:latest
    container_name: tms-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - tms-db-data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d

volumes:
  tms-db-data:
    driver: local